<a href="https://colab.research.google.com/github/RitukumariBE/Numpy-Basics/blob/main/Numpy_Student_Marks_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project on the Numpy student Marks Analytics

In [ ]:
import numpy as np


In [ ]:
# This array has 10 rows (students) and 5 columns (subjects)
marks = np.random.randint(1,100,50).reshape(10,5)

In [ ]:
marks.shape

(10, 5)

In [ ]:
marks

array([[12, 44, 80, 87, 82],
       [46, 88, 48, 70, 39],
       [74, 20, 97, 54, 24],
       [42, 65, 15, 69, 18],
       [ 8, 78, 39, 41, 88],
       [ 3, 60, 59, 63, 49],
       [15, 62, 90, 80, 69],
       [46, 56, 94,  6, 28],
       [51, 34, 56, 89, 79],
       [81, 95, 78, 35, 41]])

In [ ]:
marks[0] # accessing the marks of student 1

array([12, 44, 80, 87, 82])

In [ ]:
marks[:,1] # accessing the subject 2 marks of all students

array([44, 88, 20, 65, 78, 60, 62, 56, 34, 95])

In [ ]:
marks[0:3,3:]

array([[87, 82],
       [70, 39],
       [54, 24]])